# Generated by Django 5.1.6 on 2026-08-10 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invested', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Stock'), ('MUTUAL_FUND', 'Mutual Fund'), ('SIP', 'SIP'), ('GOLD', 'Gold'), ('CRYPTO', 'Cryptocurrency'), ('ETF', 'ETF'), ('OTHER', 'Other')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('average_buy_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Stock'), ('MUTUAL_FUND', 'Mutual Fund'), ('SIP', 'SIP'), ('GOLD', 'Gold'), ('CRYPTO', 'Cryptocurrency'), ('ETF', 'ETF'), ('OTHER', 'Other')], max_length=20)),
                ('alert_price_above', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('alert_price_below', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
