# Generated by Django 5.1.6 on 2026-08-11 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_country_user_created_at_user_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=25)),
                ('city', models.CharField(default='Mumbai', max_length=100)),
                ('country', models.CharField(default='India', max_length=50)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('other_monthly_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('estimated_monthly_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('current_savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('emergency_fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('risk_profile', models.CharField(default='Moderate', max_length=20)),
                ('budget_method', models.CharField(default='50/30/20', max_length=20)),
                ('financial_priorities', models.TextField(blank=True, default='Save more, Build emergency fund')),
                ('is_onboarding_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
