# Generated by Django 5.1.6 on 2026-08-11 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('savings_target', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('emergency_fund_target', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('investment_target', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('debt_payment_target', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('financial_health_score', models.IntegerField(default=50)),
                ('risk_profile', models.CharField(default='Moderate', max_length=20)),
                ('budget_method', models.CharField(default='50/30/20', max_length=20)),
                ('plan_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
